# Generated by Django 3.1.5 on 2021-02-03 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20210203_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_rating',
            unique_together={('user', 'movie')},
        ),
    ]
