# Generated by Django 3.1.5 on 2021-04-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210323_1724'),
        ('movies', '0005_auto_20210323_1353'),
    ]

    operations = [
    ]
