# Generated by Django 3.1.5 on 2021-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_merge_20210404_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors_name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors_name_eg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres_name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres_name_eg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name_eg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='actors_urls',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='actors_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='country',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
