# Generated by Django 3.1.5 on 2021-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210622_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
