# Generated by Django 3.1.5 on 2021-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210622_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_English',
            field=models.BooleanField(default=True),
        ),
    ]
