# Generated by Django 3.1.5 on 2021-06-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_is_english'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_English',
            new_name='is_english',
        ),
    ]
